package:
  name: reprounzip
  version: !!str _REPLACE_version_REPLACE_

source:
  fn: reprounzip.tar.gz
  url: _REPLACE_url_REPLACE_

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - reprounzip = reprounzip:main
    #
    # Would create an entry point called vistrails that calls vistrails.main()

    - reprounzip = reprounzip.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
  string: _REPLACE_buildstr_REPLACE_

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools  # for pkg_resources
    - pyyaml
    - requests
    - rpaths >=0.8
    - usagestats >=0.3

test:
  # Python imports
  imports:
    - reprounzip.main
    - reprounzip.unpackers.default

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - reprounzip --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://vida-nyu.github.io/reprozip/
  license: BSD License
  summary: 'Linux tool enabling reproducible experiments (unpacker)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
